name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change to your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Ensure this secret is added to your GitHub repository

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-54-172-192-180.compute-1.amazonaws.com 'cd /var/www/html/TerpPlates && git pull origin main'

